# Generated by Django 3.1 on 2020-09-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerStudentData',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('Mark', models.CharField(max_length=2)),
                ('Level', models.CharField(max_length=20)),
                ('NOQ', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
