# Generated by Django 3.1 on 2020-09-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_perstudentdata_questioncol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perstudentdata',
            name='QuestionCol',
        ),
        migrations.AddField(
            model_name='perstudentdata',
            name='Chemistry',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='perstudentdata',
            name='English',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='perstudentdata',
            name='Math',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='perstudentdata',
            name='Physics',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
