# Generated by Django 3.1 on 2020-11-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20200927_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerQuestionDataColl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
