# Generated by Django 3.1 on 2020-11-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_perquestiondatacoll'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerQuestionDataColl',
            new_name='PerQuestionForCerf',
        ),
    ]
