# Generated by Django 3.1 on 2020-11-09 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Dashboard', '0006_levelupdecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerQuestionForCertificate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('QuesId', models.CharField(max_length=50, null=True)),
                ('Solved', models.CharField(max_length=50, null=True)),
                ('SolvedTimes', models.CharField(max_length=50, null=True)),
                ('TimeTaken', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PerQuestionForCerf',
        ),
    ]
