# Generated by Django 3.1 on 2020-11-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_auto_20201109_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perquestionforcertificate',
            name='Solved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
