# Generated by Django 3.1 on 2020-11-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_auto_20201109_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelupdecision',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
