# Generated by Django 3.1 on 2020-11-09 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0009_levelupdecision_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='levelUpDecisions',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(null=True)),
                ('percentage', models.CharField(max_length=50, null=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='levelUpDecision',
        ),
    ]
