# Generated by Django 3.1 on 2020-11-09 18:33

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_auto_20201110_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelupdecisions',
            name='User',
        ),
        migrations.AddField(
            model_name='levelupdecisions',
            name='User',
            field=models.CharField(max_length=50, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
