# Generated by Django 3.1 on 2020-11-09 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0012_auto_20201110_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelupdecisions',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
