# Generated by Django 3.1 on 2020-11-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_auto_20201110_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelupdecision',
            name='User',
        ),
    ]
