# Generated by Django 3.1 on 2020-11-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_remove_levelupdecision_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='levelUpDecision',
        ),
    ]
