# Generated by Django 3.1 on 2020-09-06 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('T_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdetail',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
