# Generated by Django 3.1 on 2020-11-09 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerQuestionForCertificate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('QuesId', models.CharField(max_length=50, null=True)),
                ('Solved', models.BooleanField(default=False, null=True)),
                ('SolvedTimes', models.CharField(max_length=50, null=True)),
                ('TimeTaken', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='perstudentdata',
            name='Chemistry',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='perstudentdata',
            name='English',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='perstudentdata',
            name='Math',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='perstudentdata',
            name='Physics',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='levelUpDec',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(null=True)),
                ('percentage', models.CharField(max_length=50, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
