# Generated by Django 3.1 on 2020-11-10 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0002_auto_20201110_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerStudentCache',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('QuesID', models.CharField(blank=True, max_length=255)),
                ('Question', models.TextField()),
                ('ans', models.CharField(blank=True, max_length=255)),
                ('UserAns', models.CharField(blank=True, max_length=255)),
                ('Solved', models.BooleanField(default=False, null=True)),
                ('QTime', models.CharField(blank=True, max_length=255)),
                ('TimeTaken', models.CharField(blank=True, max_length=255)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
