# Generated by Django 3.1 on 2020-11-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_perstudentcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='perstudentcache',
            name='Did',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
