# Generated by Django 3.1 on 2020-11-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_perstudentcache_did'),
    ]

    operations = [
        migrations.AddField(
            model_name='perquestionforcertificate',
            name='IntQuesID',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='perstudentcache',
            name='IntQuesID',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
