# Generated by Django 3.1 on 2020-11-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_auto_20201110_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perquestionforcertificate',
            name='TimeTaken',
        ),
        migrations.AddField(
            model_name='perquestionforcertificate',
            name='MaxTimeTaken',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perquestionforcertificate',
            name='MinTimeTaken',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
