# Generated by Django 3.1 on 2020-11-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_auto_20201110_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perquestionforcertificate',
            name='MaxTimeTaken',
        ),
        migrations.RemoveField(
            model_name='perquestionforcertificate',
            name='MinTimeTaken',
        ),
        migrations.AddField(
            model_name='perquestionforcertificate',
            name='TimeTaken',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
