# Generated by Django 3.1 on 2020-11-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_auto_20201110_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perstudentcache',
            name='IntQuesID',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
