# Generated by Django 3.1 on 2020-11-10 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0008_auto_20201110_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerQuestionForCertificates',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('QuesId', models.CharField(max_length=50, null=True)),
                ('IntQuesID', models.CharField(blank=True, max_length=255)),
                ('Solved', models.BooleanField(default=False, null=True)),
                ('SolvedTimes', models.CharField(max_length=50, null=True)),
                ('TimeTaken', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PerQuestionForCertificate',
        ),
    ]
