# Generated by Django 3.1 on 2020-12-16 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0010_auto_20201110_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarked',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('QuesID', models.CharField(blank=True, max_length=255)),
                ('IntQuesID', models.CharField(max_length=255, null=True)),
                ('Question', models.TextField()),
                ('optA', models.CharField(blank=True, max_length=255)),
                ('optB', models.CharField(blank=True, max_length=255)),
                ('optC', models.CharField(blank=True, max_length=255)),
                ('optD', models.CharField(blank=True, max_length=255)),
                ('ans', models.CharField(blank=True, max_length=255)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
