# Generated by Django 3.1 on 2020-09-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicsques',
            old_name='mathID',
            new_name='physicsID',
        ),
        migrations.RenameField(
            model_name='physicsques',
            old_name='teacherID',
            new_name='teacherName',
        ),
    ]
