# Generated by Django 3.1 on 2020-09-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20200918_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemistryQues',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.TextField()),
                ('optA', models.CharField(max_length=255)),
                ('optB', models.CharField(max_length=255)),
                ('optC', models.CharField(max_length=255)),
                ('optD', models.CharField(max_length=255)),
                ('ans', models.CharField(max_length=10)),
                ('mark', models.IntegerField()),
                ('level', models.IntegerField()),
                ('teacherName', models.CharField(max_length=20)),
                ('chemistryID', models.CharField(blank=True, max_length=20)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnglishQues',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.TextField()),
                ('optA', models.CharField(max_length=255)),
                ('optB', models.CharField(max_length=255)),
                ('optC', models.CharField(max_length=255)),
                ('optD', models.CharField(max_length=255)),
                ('ans', models.CharField(max_length=10)),
                ('mark', models.IntegerField()),
                ('level', models.IntegerField()),
                ('teacherName', models.CharField(max_length=20)),
                ('englishID', models.CharField(blank=True, max_length=20)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
