# Generated by Django 3.1 on 2020-09-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_chemistryques_englishques'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allques',
            name='teacherID',
        ),
        migrations.AddField(
            model_name='allques',
            name='subjID',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='allques',
            name='teacherName',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
