# Generated by Django 3.1 on 2020-09-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20200921_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='allques',
            name='subjModel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chemistryques',
            name='chemistryModel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='englishques',
            name='englishModel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mathques',
            name='mathModel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='physicsques',
            name='physicsModel',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
