# Generated by Django 3.1 on 2020-09-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20200923_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='allques',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chemistryques',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='englishques',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mathques',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='physicsques',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
