# Generated by Django 3.1 on 2020-11-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_auto_20200930_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChemistryQuesLevel1',
        ),
        migrations.DeleteModel(
            name='ChemistryQuesLevel2',
        ),
        migrations.DeleteModel(
            name='ChemistryQuesLevel3',
        ),
        migrations.DeleteModel(
            name='ChemistryQuesMark1',
        ),
        migrations.DeleteModel(
            name='ChemistryQuesMark2',
        ),
        migrations.DeleteModel(
            name='EnglishQuesLevel1',
        ),
        migrations.DeleteModel(
            name='EnglishQuesLevel2',
        ),
        migrations.DeleteModel(
            name='EnglishQuesLevel3',
        ),
        migrations.DeleteModel(
            name='EnglishQuesMark1',
        ),
        migrations.DeleteModel(
            name='EnglishQuesMark2',
        ),
        migrations.DeleteModel(
            name='MathQuesLevel1',
        ),
        migrations.DeleteModel(
            name='MathQuesLevel2',
        ),
        migrations.DeleteModel(
            name='MathQuesLevel3',
        ),
        migrations.DeleteModel(
            name='MathQuesMark1',
        ),
        migrations.DeleteModel(
            name='MathQuesMark2',
        ),
        migrations.DeleteModel(
            name='PhysicsQuesLevel1',
        ),
        migrations.DeleteModel(
            name='PhysicsQuesLevel2',
        ),
        migrations.DeleteModel(
            name='PhysicsQuesLevel3',
        ),
        migrations.DeleteModel(
            name='PhysicsQuesMark1',
        ),
        migrations.DeleteModel(
            name='PhysicsQuesMark2',
        ),
    ]
