# Generated by Django 3.1 on 2020-11-09 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20201107_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemistryques',
            name='intQuesID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.allques'),
        ),
        migrations.AddField(
            model_name='englishques',
            name='intQuesID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.allques'),
        ),
        migrations.AddField(
            model_name='mathques',
            name='intQuesID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.allques'),
        ),
        migrations.AddField(
            model_name='physicsques',
            name='intQuesID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.allques'),
        ),
    ]
