# Generated by Django 3.1 on 2020-11-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20201109_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='allques',
            name='lessTimeTaken',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='allques',
            name='modLevel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='allques',
            name='modMark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='allques',
            name='moreTimeTaken',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chemistryques',
            name='lessTimeTaken',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chemistryques',
            name='modLevel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chemistryques',
            name='modMark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chemistryques',
            name='moreTimeTaken',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='englishques',
            name='lessTimeTaken',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='englishques',
            name='modLevel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='englishques',
            name='modMark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='englishques',
            name='moreTimeTaken',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mathques',
            name='lessTimeTaken',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mathques',
            name='modLevel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mathques',
            name='modMark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mathques',
            name='moreTimeTaken',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='physicsques',
            name='lessTimeTaken',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='physicsques',
            name='modLevel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='physicsques',
            name='modMark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='physicsques',
            name='moreTimeTaken',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
