# Generated by Django 3.1 on 2020-11-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_auto_20201109_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allques',
            name='modLevel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='allques',
            name='modMark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chemistryques',
            name='modLevel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chemistryques',
            name='modMark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='englishques',
            name='modLevel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='englishques',
            name='modMark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mathques',
            name='modLevel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mathques',
            name='modMark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='physicsques',
            name='modLevel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='physicsques',
            name='modMark',
            field=models.IntegerField(),
        ),
    ]
