# Generated by Django 3.1 on 2020-08-30 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('image', models.ImageField(default='pic.jpg', null=True, upload_to='profile_pics')),
                ('dob', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=10, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('father', models.CharField(max_length=10, null=True)),
                ('mother', models.CharField(max_length=10, null=True)),
                ('plus2name', models.CharField(max_length=10, null=True)),
                ('plus2board', models.CharField(max_length=10, null=True)),
                ('plus2year', models.CharField(max_length=10, null=True)),
                ('plus2percent', models.CharField(max_length=10, null=True)),
                ('slcname', models.CharField(max_length=10, null=True)),
                ('slcboard', models.CharField(max_length=10, null=True)),
                ('slcyear', models.CharField(max_length=10, null=True)),
                ('slcpercent', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
